// packages/client/src/components/Header.tsx
import { Link } from 'react-router-dom';

import TagSearchBar from './TagSearchBar';
import { User } from '../api/user';

const Header = ({ user }: { user: User }) => (
  <>
    <div className="header">
      <div className="header-content">
        <Link to="/">
          <img src="/assets/images/logo.png" />
        </Link>
        <ul>
          <li>
            <Link to="/"> Bilder </Link>
          </li>
          <li>
            <Link to="/about"> Om oss </Link>
          </li>
          {user?.role != 'None' ? (
            <li>
              <Link to="/admin">Admin </Link>
            </li>
          ) : null}
        </ul>
        <div className="info">
          <TagSearchBar />
        </div>
      </div>
    </div>
  </>
);

export default Header;

// packages/client-svelte/src/routes/header.svelte
<script lang="ts">
	import TagSearchBar from './tag-search-bar.svelte';

	const user = { role: 'None' };
</script>

<div class="header">
	<div class="header-content">
		<a href="/">
			<img src="/assets/images/logo.png" alt="" />
		</a>
		<ul>
			<li>
				<a href="/"> Bilder </a>
			</li>
			<li>
				<a href="/about"> Om oss </a>
			</li>
			{#if user?.role != 'None'}
				<li>
					<a href="/admin">Admin </a>
				</li>
			{/if}
		</ul>
		<div class="info">
			<TagSearchBar />
		</div>
	</div>
</div>
