// packages/client/src/components/admin/Index.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import { observer } from 'mobx-react';
import { get } from 'lodash-es';

@observer
class AdminIndex extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      fullname: props.user.fullName,
    };
  }

  componentWillReceiveProps(newProps, oldProps) {
    this.setState({ fullname: newProps.user.fullName });
  }

  changeNameSubmit(event) {
    this.props.user.setFullName(this.state.fullname).then(
      (() => {
        this.setState({ saveSuccess: true });
      }).bind(this)
    );

    event.preventDefault();
  }

  changeFullname(event) {
    this.setState({ fullname: event.target.value });
  }

  logout(event) {
    this.props.user.logout();
  }

  render() {
    if (!this.props.user.isLoggedIn || this.props.user.role == 'None') {
      return <p>Du får inte vara här.</p>;
    }

    const saveSuccess = get(this.state, 'saveSuccess');
    const fullname = get(this.state, 'fullname', this.props.user.fullName);

    return (
      <div>
        <p> Välkommen {this.props.user.cid}. </p>

        <form onSubmit={this.changeNameSubmit.bind(this)}>
          <label>Ditt namn:</label>
          <input
            type="text"
            value={fullname}
            onChange={this.changeFullname.bind(this)}
          />
          <button type="submit">Spara</button>
          {saveSuccess ? <span>Sparat!</span> : null}
          <p>
            {' '}
            Det är detta namnet som syns på dina bilder, om du inte har satt
            något namn syns ditt cid.
          </p>
        </form>
        <button onClick={this.logout.bind(this)}>Logga ut</button>
        <hr />
        <Link to="/admin/gallery">
          <button type="button">Hantera gallerier</button>
        </Link>
        <Link to="/admin/members">
          <button type="button">Hantera medlemmar</button>
        </Link>
      </div>
    );
  }
}

export default AdminIndex;

// packages/client-svelte/src/routes/admin/+page.svelte
<script lang="ts">
	import { goto, invalidate } from '$app/navigation';
	import { json } from '$lib';
	import { changeName, logoutUser } from '$lib/api/user.js';

	export let data;

	let saveSuccess = false;

	async function changeNameSubmit(form: { fullname: string }) {
		data.user && (await changeName({ fetch }, data.user, form.fullname));
		saveSuccess = true;
		invalidate('app:user');
	}

	function logout() {
		logoutUser({ fetch });
		invalidate('app:user');
		goto('/');
	}
</script>

<div>
	<p>Välkommen {data.user?.cid}.</p>

	<form use:json={changeNameSubmit}>
		<label for="fullname">Ditt namn:</label>
		<input id="fullname" name="fullname" type="text" value={data.user?.fullname} />
		<button type="submit">Spara</button>
		{#if saveSuccess}
			<span>Sparat!</span>
		{/if}
		<p>
			Det är detta namnet som syns på dina bilder, om du inte har satt något namn syns ditt cid.
		</p>
	</form>
	<button on:click={logout}>Logga ut</button>
	<hr />
	<a href="/admin/gallery">
		<button type="button">Hantera gallerier</button>
	</a>
	<a href="/admin/members">
		<button type="button">Hantera medlemmar</button>
	</a>
</div>
