// packages/client-svelte/src/routes/about/+page.svelte
<div class="wrapper">
	<div class="site-content about-us">
		<h2>Om oss</h2>
		<p>
			DFoto är Datateknologsektionens fotoförening. Vår ambition är att genom foto och film föreviga
			alla arrangemang Datateknologen går på. Allt ifrån iDrotts legendariska aktiviteter, till D6s
			storslagna fester och Deltas episka pubar.
		</p>
		<p>
			Du kan komma i kontakt med oss genom att maila
			<a href="mailto:dfoto@dtek.se">dfoto@dtek.se</a> eller skriva till vår{' '}
			<a href="https://www.facebook.com/dfotochalmers/">Facebooksida</a>.
		</p>
		<h3>Vi ses genom kameralinsen!</h3>
	</div>
</div>

// packages/client/src/routes/about.tsx
const About = () => (
  <div className="wrapper">
    <div className="site-content about-us">
      <h2>Om oss</h2>
      <p>
        DFoto är Datateknologsektionens fotoförening. Vår ambition är att genom
        foto och film föreviga alla arrangemang Datateknologen går på. Allt
        ifrån iDrotts legendariska aktiviteter, till D6s storslagna fester och
        Deltas episka pubar.
      </p>
      <p>
        {' '}
        Du kan komma i kontakt med oss genom att maila{' '}
        <a href="mailto:dfoto@dtek.se">dfoto@dtek.se</a> eller skriva till vår{' '}
        <a href="https://www.facebook.com/dfotochalmers/">Facebooksida</a>.
      </p>
      <h3>Vi ses genom kameralinsen!</h3>
    </div>
  </div>
);

export default About;
