// packages/client/src/components/admin/UploadImagesForm.tsx
import { FormEvent, useRef, useState } from 'react';
import { ImageGalleryList } from '../../ImageStore';

export const UploadImagesForm = ({
  galleryImageList,
}: {
  galleryImageList: ImageGalleryList;
}) => {
  const fileInput = useRef<HTMLInputElement>(null);
  const [percentDone, setPercentDone] = useState(0);
  const [isUploading, setIsUploading] = useState(false);

  function onSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setIsUploading(true);

    const formData = new FormData();
    const files = fileInput.current.files;

    for (const file of files) {
      formData.append('photos', file);
    }

    const onProgress = (percent) => {
      setPercentDone(percent);
      if (percent >= 100) {
        setIsUploading(false);
      }
    };

    galleryImageList.addImages(formData, onProgress);
  }
  const formUpload = (
    <form onSubmit={onSubmit}>
      <h1> Ladda upp bilder </h1>
      <input
        ref={fileInput}
        id="image"
        type="file"
        className="u-full-width"
        name="photos"
        accept="image/*"
        multiple
      />
      <input
        className="button-primary button-orange"
        type="submit"
        value="Upload"
        name="submit"
      />
    </form>
  );

  const progressBar = (
    <div>
      <p>Laddar upp: {percentDone}% klart.</p>
    </div>
  );

  return <div>{isUploading ? progressBar : formUpload}</div>;
};

// packages/client-svelte/src/routes/admin/gallery/edit/[id]/upload-images-form.svelte
<script lang="ts">
	import { progress } from '$lib';
	import type { Gallery } from '$lib/api/gallery';

	let uploadProgress = -1;
	$: uploading = uploadProgress !== -1;

	export let gallery: Gallery;
</script>

<form
	action="/v1/image/{gallery._id}"
	use:progress={(event) => {
		uploadProgress = (event.loaded / event.total) * 100;
		if (uploadProgress >= 100) {
			uploadProgress = -1;
		}
	}}
>
	<h1>Ladda upp bilder</h1>
	<input id="image" type="file" class="u-full-width" name="photos" accept="image/*" multiple />
	<input class="button-primary button-orange" type="submit" value="Upload" />
</form>
{#if uploading}
	<div>
		<p>Laddar upp: {uploadProgress}% klart.</p>
	</div>
{/if}
