// packages/client-svelte/src/routes/header.svelte
<script lang="ts">
	import TagSearchBar from './tag-search-bar.svelte';

	const user = { role: 'None' };
</script>

<div class="header">
	<div class="header-content">
		<a href="/">
			<img src="/assets/images/logo.png" alt="" />
		</a>
		<ul>
			<li>
				<a href="/"> Bilder </a>
			</li>
			<li>
				<a href="/about"> Om oss </a>
			</li>
			{#if user?.role != 'None'}
				<li>
					<a href="/admin">Admin </a>
				</li>
			{/if}
		</ul>
		<div class="info">
			<TagSearchBar />
		</div>
	</div>
</div>

// packages/client/src/components/Header.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import { observer } from 'mobx-react';

import TagSearchBar from './TagSearchBar';
import uiState from '../UiState';

@observer
class Header extends React.Component {
  render() {
    return (
      <div className="header">
        <div className="header-content">
          <Link to="/">
            <img src="/assets/images/logo.png" />
          </Link>
          <ul>
            <li>
              <Link to="/"> Bilder </Link>
            </li>
            <li>
              <Link to="/about"> Om oss </Link>
            </li>
            {uiState.user.isLoggedIn && uiState.user.role != 'None' ? (
              <li>
                <Link to="/admin">Admin </Link>
              </li>
            ) : null}
          </ul>
          <div className="info">
            <TagSearchBar />
          </div>
        </div>
      </div>
    );
  }
}

export default Header;
