// packages/client-svelte/src/routes/admin/gallery/edit/[id]/upload-images-form.svelte
<script lang="ts">
	import { progress } from '$lib';
	import type { Gallery } from '$lib/api/gallery';

	let uploadProgress = -1;
	$: uploading = uploadProgress !== -1;

	export let gallery: Gallery;
</script>

<form
	action="/v1/image/{gallery._id}"
	use:progress={(event) => {
		uploadProgress = (event.loaded / event.total) * 100;
		if (uploadProgress >= 100) {
			uploadProgress = -1;
		}
	}}
>
	<h1>Ladda upp bilder</h1>
	<input id="image" type="file" class="u-full-width" name="photos" accept="image/*" multiple />
	<input class="button-primary button-orange" type="submit" value="Upload" />
</form>
{#if uploading}
	<div>
		<p>Laddar upp: {uploadProgress}% klart.</p>
	</div>
{/if}

// src/client/components/admin/UploadImagesForm.jsx
import _ from 'lodash';
import React from 'react';
import uiState from '../../UiState';
import PropTypes from 'prop-types';

export default class UploadImagesForm extends React.Component {
  static propTypes = {
    galleryImageList: PropTypes.object
  };
  
  constructor(props) {
    super(props);
    
    this.state = {
      percentDone: 0,
      isUploading: false
    };
  }
  
  onSubmit(event) {
    event.preventDefault();
    this.setState({ isUploading: true });
    
    const formData = new FormData();
    const fileElement = document.getElementById('image');
    const files = fileElement.files;
    _.forEach(files, file => {
      formData.append('photos', file);
    });
    
    const onProgress = (percent => {
      this.setState({ percentDone: percent });
      
      if (percent >= 100) {
        this.setState({ isUploading: false });
      }
    }).bind(this);
    
    this.props.galleryImageList.addImages(formData, onProgress);
  }
  
  render() {
    const {percentDone, isUploading} = this.state;
    
    const formUpload = (
      <form onSubmit={ this.onSubmit.bind(this) }>
        <h1> Ladda upp bilder </h1>
        <input id="image" type="file" className="u-full-width" name="photos" accept="image/*" multiple />
        <input className="button-primary button-orange" type="submit" value="Upload" name="submit" />
      </form>
    );

    const progressBar = (
      <div>
        <p>Laddar upp: {percentDone}% klart.</p>
      </div>
    );

    return (
      <div>
        { isUploading ? progressBar : formUpload }
      </div>
    );
  }
}
